mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: 12345
    MYSQL_USER: app_user
    MYSQL_PASSWORD: 1234

todoapp:
  namespace: todoapp
  image:
    repository: orestprogrammer/todoapp
    tag: "37fc28707af37fd3c32615f6d180e057b2f503c2"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secrets:
    SECRET_KEY: zdfsadfsadfsfs
    DB_NAME: app_db
    DB_USER: app_user
    DB_PASSWORD: 1234
    DB_HOST: mysql-0.mysql.mysql.svc.cluster.local

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      avarageUtilization: 70
    memory:
      avarageUtilization: 70

  volumes:
    persistentVolume:
      capacity: "1Gi"
    persistentVolumeClaim:
      requestStorage: "1Gi"